apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-python
  namespace: sds-cp
  labels:
    app: connectors-python
    
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectors-python
  template:
    metadata:
      labels:
        app: connectors-python
    spec:
      imagePullSecrets:
        - name: intersystems-container-registry-secret
      containers:
        - name: sds-connectors-python
          image: containers.intersystems.com/iscinternal/sds-service/sds-connectors-python:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
