apiVersion: v1
kind: Service
metadata:
  name: connectors-python
  namespace: {{.Values.app.namespace}}
  labels:
    app: connectors-python
    
spec:
  selector:
    app: connectors-python
  ports:
    - name: connectors-python
      port: {{.Values.service.port}}
      targetPort: 8000
  type: LoadBalancer
    