{{- if eq (toString .Values.admin.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: connectors-python
  namespace: {{.Release.Name}}
  labels:
    app: connectors-python
    
spec:
  selector:
    app: connectors-python
  ports:
    - name: management
      port: {{ .Values.admin.port }}
      targetPort: 8000
  type: LoadBalancer
{{- end }}